#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Installs the Switchyard background server and its menu bar companion as
# per-user LaunchAgents, sets up a `sy` Codex profile, and aliases `codex` to
# use it.
#
# Every step is idempotent and never overwrites a file you have edited.
# Run with --dry-run to print what would happen.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

# shellcheck source=scripts/macos/common.sh
source "$SCRIPT_DIR/common.sh"

# Runs a command, or prints it when dry running.
run() {
  if (( DRY_RUN )); then
    say "  would run: $*"
  else
    "$@"
  fi
}

# Writes stdin to a file, leaving an existing file untouched.
write_once() {
  local path="$1"
  if [[ -f "$path" ]]; then
    say "  keeping existing $path"
    cat >/dev/null
    return
  fi
  if (( DRY_RUN )); then
    say "  would create $path"
    cat >/dev/null
  else
    mkdir -p "$(dirname "$path")"
    cat > "$path"
    say "  created $path"
  fi
}

# Writes stdin to a file, keeping any existing version as a timestamped backup.
write_with_backup() {
  local path="$1"
  if (( DRY_RUN )); then
    [[ -f "$path" ]] && say "  would back up $path"
    say "  would write $path"
    cat >/dev/null
    return
  fi
  mkdir -p "$(dirname "$path")"
  local incoming
  incoming="$(mktemp)"
  cat > "$incoming"
  if [[ -f "$path" ]] && cmp -s "$incoming" "$path"; then
    say "  $path is already up to date"
    rm -f "$incoming"
    return
  fi
  if [[ -f "$path" ]]; then
    local backup
    backup="$path.switchyard-backup.$(date +%Y%m%d%H%M%S)"
    cp "$path" "$backup"
    say "  backed up $path to $backup"
  fi
  cat "$incoming" > "$path"
  rm -f "$incoming"
  say "  wrote $path"
}

# Builds a whole Codex config that routes through Switchyard, derived from the
# config you use now.
#
# Codex.app cannot use the sy profile: it writes profiles as [profiles.NAME]
# tables inside config.toml, which its own bundled CLI now rejects as legacy
# config. Inlining the settings at the top level is the one format both the
# app and the CLI accept, so this is a second config.toml you swap in rather
# than a profile you select.
#
# Regenerating from an already-swapped config.toml yields the same file, since
# the keys this adds are stripped before they are written back.
write_codex_switchyard_config() {
  local source="$1" target="$2"
  if [[ ! -f "$source" ]]; then
    say "  no $source to derive from, skipping"
    return
  fi
  if (( DRY_RUN )); then
    say "  would write $target"
    return
  fi

  local body
  body="$(mktemp)"
  # Drop what this file replaces: the top-level model selection, any
  # model_provider, and an earlier copy of the provider table.
  awk '
    BEGIN { preamble = 1; skip_table = 0 }
    /^[[:space:]]*\[/ {
      preamble = 0
      skip_table = ($0 ~ /^[[:space:]]*\[model_providers\.sy\][[:space:]]*\]?[[:space:]]*$/)
    }
    preamble && /^[[:space:]]*(model|model_provider)[[:space:]]*=/ { next }
    !skip_table { print }
  ' "$source" > "$body"

  {
    echo "# Generated by the Switchyard installer. Do not edit; edit config.toml"
    echo "# and reinstall, and this file is rebuilt from it."
    echo "#"
    echo "# This is config.toml with Switchyard routing inlined, for Codex.app,"
    echo "# which cannot use the sy profile. Swap it in and out with:"
    echo "#   cp ~/.codex/config.toml.sy ~/.codex/config.toml       # route"
    echo "#   cp ~/.codex/config.toml.direct ~/.codex/config.toml   # stop routing"
    echo "model = \"switchyard\""
    echo "model_provider = \"sy\""
    cat "$body"
    echo
    echo "[model_providers.sy]"
    echo "name = \"Switchyard\""
    echo "base_url = \"http://127.0.0.1:$SY_PORT/v1\""
    echo "wire_api = \"responses\""
    echo "requires_openai_auth = true"
  } > "$target"
  rm -f "$body"
  say "  wrote $target"
}

# Writes stdin to a file, replacing it. Used only for files this script owns.
write_always() {
  local path="$1"
  if (( DRY_RUN )); then
    say "  would write $path"
    cat >/dev/null
  else
    mkdir -p "$(dirname "$path")"
    cat > "$path"
    say "  wrote $path"
  fi
}

if [[ "$(uname -s)" != "Darwin" ]]; then
  say "This installer is for macOS only." >&2
  exit 1
fi

step "Building release binaries"
run cargo build --release --manifest-path "$REPO_ROOT/Cargo.toml" \
  -p switchyard-server -p switchyard-menubar

step "Installing binaries into $SY_HOME/bin"
run mkdir -p "$SY_HOME/bin" "$SY_HOME/logs"
for binary in switchyard-server switchyard-menubar; do
  run install -m 755 "$REPO_ROOT/target/release/$binary" "$SY_HOME/bin/$binary"
done

step "Writing server config"
# The composite router from examples/run_codex.sh: Terra classifies each user
# turn and sets the tier, Stage drives the tool loop underneath it.
write_once "$SY_HOME/composite.toml" <<'EOF'
schema_version = 1

[llm_clients.chatgpt_backend]
format = "openai_responses"
base_url = "https://chatgpt.com/backend-api/codex"
forward_auth = true

[targets.capable]
id = "gpt-5.6-sol"
llm_client = "chatgpt_backend"

[targets.efficient]
id = "gpt-5.6-luna"
llm_client = "chatgpt_backend"

# chatgpt.com/backend-api/codex is Codex CLI's own private endpoint, not the
# public OpenAI Responses API. It 400s unless store=false and stream=true are
# set explicitly, and it rejects max_output_tokens outright, so the
# classifier's own token cap has to be dropped before the request goes out.
[targets.terra]
id = "gpt-5.6-terra"
llm_client = "chatgpt_backend"
extra_body = { store = false, stream = true }
omit_body_fields = ["max_output_tokens"]

[routes.switchyard]
id = "switchyard"
type = "composite"

[routes.switchyard.classifier]
target = "terra"
base_threshold = 0.5
classify_trigger = "user_turn"

[routes.switchyard.stage]
capable_target = "capable"
efficient_target = "efficient"
confidence_threshold = 0.5
EOF

step "Writing menu bar settings"
# Rates are list prices per million tokens and are only used to estimate
# savings. Edit them to match what you actually pay.
write_once "$SY_HOME/menubar.toml" <<EOF
server_url = "http://127.0.0.1:$SY_PORT"
routing_log = "$SY_HOME/routing.jsonl"
config_file = "$SY_HOME/composite.toml"
launchd_label = "$SERVER_LABEL"
refresh_seconds = 30

# The model the traffic is assumed to have used without Switchyard. Savings
# are the difference between that bill and what actually ran, with
# Switchyard's own classifier calls counted against it.
baseline_model = "gpt-5.6-sol"

[prices."gpt-5.6-sol"]
input_per_mtok = 1.25
cached_input_per_mtok = 0.125
output_per_mtok = 10.0

[prices."gpt-5.6-luna"]
input_per_mtok = 0.25
cached_input_per_mtok = 0.025
output_per_mtok = 2.0

[prices."gpt-5.6-terra"]
input_per_mtok = 0.05
cached_input_per_mtok = 0.005
output_per_mtok = 0.4
EOF

step "Validating the server config"
if (( DRY_RUN )); then
  say "  would run: $SY_HOME/bin/switchyard-server --config $SY_HOME/composite.toml --dry-run"
else
  "$SY_HOME/bin/switchyard-server" --config "$SY_HOME/composite.toml" --dry-run
fi

step "Writing LaunchAgents"
write_always "$LAUNCH_AGENTS/$SERVER_LABEL.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$SERVER_LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$SY_HOME/bin/switchyard-server</string>
    <string>--config</string>
    <string>$SY_HOME/composite.toml</string>
    <string>--host</string>
    <string>127.0.0.1</string>
    <string>--port</string>
    <string>$SY_PORT</string>
    <string>--routing-log-file</string>
    <string>$SY_HOME/routing.jsonl</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>$SY_HOME/logs/server.log</string>
  <key>StandardErrorPath</key>
  <string>$SY_HOME/logs/server.err.log</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>RUST_LOG</key>
    <string>info</string>
  </dict>
</dict>
</plist>
EOF

# SuccessfulExit false means the Quit menu item stays quit, while a crash is
# still restarted. Aqua-only, since there is no menu bar without a login session.
write_always "$LAUNCH_AGENTS/$MENUBAR_LABEL.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$MENUBAR_LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$SY_HOME/bin/switchyard-menubar</string>
    <string>$SY_HOME/menubar.toml</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>LimitLoadToSessionType</key>
  <string>Aqua</string>
  <key>StandardOutPath</key>
  <string>$SY_HOME/logs/menubar.log</string>
  <key>StandardErrorPath</key>
  <string>$SY_HOME/logs/menubar.err.log</string>
</dict>
</plist>
EOF

step "Loading LaunchAgents"
for label in "$SERVER_LABEL" "$MENUBAR_LABEL"; do
  if (( DRY_RUN )); then
    say "  would reload gui/$UID/$label"
    continue
  fi
  launchctl bootout "gui/$UID/$label" 2>/dev/null || true
  # bootout returns before the job leaves the domain, and bootstrapping a
  # service that is still shutting down fails with an I/O error.
  for _ in $(seq 50); do
    launchctl print "gui/$UID/$label" >/dev/null 2>&1 || break
    sleep 0.1
  done
  launchctl bootstrap "gui/$UID" "$LAUNCH_AGENTS/$label.plist"
  say "  loaded $label"
done

step "Adding the sy Codex profile"
# `codex --profile sy` reads ~/.codex/sy.config.toml. A [profiles.sy] table in
# config.toml is legacy config that Codex now refuses to start with, so an
# earlier install of this script has to be cleaned up first.
strip_block "$CODEX_CONFIG" "$PROFILE_START" "$PROFILE_END" "the legacy sy profile" || true

# This profile only changes which router answers. Approval and sandbox
# settings are deliberately left out, so the profile cannot loosen how Codex
# asks before it acts. Set those yourself if you want them.
write_with_backup "$CODEX_PROFILE_CONFIG" <<EOF
model = "switchyard"
model_provider = "sy"

[model_providers.sy]
name = "Switchyard"
base_url = "http://127.0.0.1:$SY_PORT/v1"
wire_api = "responses"
requires_openai_auth = true
EOF

step "Building a swap-in config for Codex.app"
# Snapshot the unrouted config so swapping back is a copy, not an edit. Taken
# only when config.toml is not already the routed one, so a reinstall while
# swapped in cannot overwrite the snapshot with a routed copy.
if [[ -f "$CODEX_CONFIG" ]] && grep -qE '^[[:space:]]*model_provider[[:space:]]*=[[:space:]]*"sy"' "$CODEX_CONFIG"; then
  say "  config.toml is already routed, keeping $CODEX_DIRECT_CONFIG as it is"
elif [[ -f "$CODEX_CONFIG" ]]; then
  if (( DRY_RUN )); then
    say "  would snapshot config.toml to $CODEX_DIRECT_CONFIG"
  else
    cp "$CODEX_CONFIG" "$CODEX_DIRECT_CONFIG"
    say "  snapshotted config.toml to $CODEX_DIRECT_CONFIG"
  fi
fi
write_codex_switchyard_config "$CODEX_CONFIG" "$CODEX_SWITCHYARD_CONFIG"

step "Aliasing codex"
for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
  if [[ -f "$rc" ]] && grep -qF "$ALIAS_START" "$rc"; then
    say "  alias already in $rc"
  elif (( DRY_RUN )); then
    say "  would add the codex alias to $rc"
  else
    printf '\n%s\nalias codex="codex --profile sy"\n%s\n' "$ALIAS_START" "$ALIAS_END" >> "$rc"
    say "  added the codex alias to $rc"
  fi
done

step "Done"
say "Server:   http://127.0.0.1:$SY_PORT  (logs in $SY_HOME/logs)"
say "Settings: $SY_HOME/menubar.toml"
say "Look for the Switchyard glyph in the menu bar."
say "Open a new shell, or run: alias codex=\"codex --profile sy\""
say ""
say "To route Codex.app too, swap its config:"
say "  cp $CODEX_SWITCHYARD_CONFIG $CODEX_CONFIG"
say "  cp $CODEX_DIRECT_CONFIG $CODEX_CONFIG   # to stop routing"
say "Restart Codex.app after swapping."
